UI_TEXT = {
    'en': {
        'brand_subtitle': 'Couple hub',
        'nav_home': 'Home',
        'nav_home_hint': 'Overview',
        'nav_todo': 'Todo',
        'nav_todo_hint': 'Tasks',
        'nav_files': 'Files',
        'nav_files_hint': 'Vault',
        'nav_chat': 'Chat',
        'nav_chat_hint': 'Notes',
        'nav_dates': 'Dates',
        'nav_dates_hint': 'Calendar',
        'nav_settings': 'Settings',
        'nav_settings_hint': 'Theme and language',
        'logout': 'Logout',
        'settings_eyebrow': 'Settings',
        'settings_title': 'Preferences',
        'settings_description': 'Choose how OurHome should look and which interface language should be used.',
        'theme_title': 'Theme',
        'theme_description': 'Switch between light and dark appearance.',
        'theme_light': 'Light',
        'theme_dark': 'Dark',
        'language_title': 'Language',
        'language_description': 'Select the preferred language for the interface.',
        'save_settings': 'Save settings',
        'account_title': 'Account',
        'account_description': 'Manage your profile, password, and account access.',
        'profile_title': 'Profile',
        'profile_description': 'Change the login, email, and display name used in OurHome.',
        'password_title': 'Password',
        'password_description': 'Update your password without leaving the current session.',
        'delete_account_title': 'Deactivate account',
        'delete_account_description': 'Hide this account and block login until it is recovered.',
        'delete_account_warning': 'Your shared spaces and messages stay in place, but login will be disabled.',
        'recover_account': 'Recover account',
        'recover_account_description': 'Restore a deactivated account and set a new password.',
        'update_profile': 'Update profile',
        'change_password': 'Change password',
        'deactivate_account': 'Deactivate account',
        'space_label': 'Space',
        'group_mode': 'Group mode',
        'shared_space': 'Shared space',
        'shared_space_description': 'Choose the space you are working in, create a new home, or add a second user.',
        'active_space': 'Active space',
        'active_space_description': 'All tasks, files, dates, and chat messages are shared inside this space.',
        'members': 'Members',
        'members_description': 'People who can see and change this shared space.',
        'space_owner': 'Owner',
        'remove_member': 'Remove',
        'add_user': 'Add user',
        'add_user_description': 'Type an existing username to give them access.',
        'add': 'Add',
        'create_space': 'Create space',
        'create_space_description': 'Use this if you want a separate home, trip, or project space.',
        'create': 'Create',
        'dashboard_eyebrow': 'CoupleHome MVP',
        'dashboard_title': 'Welcome home',
        'dashboard_description': 'Everything shared between you two lives here: tasks, files, dates, and daily notes.',
        'question': 'Question',
        'today': 'Today',
        'answer_in_chat': 'Answer it in chat when the day slows down.',
        'favorites': 'Favorites',
        'open': 'Open',
        'download': 'Download',
        'favorite': 'Favorite',
        'reminder': 'Reminder',
        'latest_notes': 'Latest notes',
        'no_notes': 'No notes yet.',
        'favorite_files_empty': 'Mark important files as favorite to keep them here.',
        'events_empty_short': 'Add anniversaries, birthdays, trips, and bills.',
        'new_task': 'New task',
        'upload_file': 'Upload file',
        'open_tasks': 'Open tasks',
        'completed': 'Completed',
        'files': 'Files',
        'upcoming': 'Upcoming',
        'todo_eyebrow': 'Todo',
        'todo_title': 'Shared task tracker',
        'todo_description': 'Requests, errands, plans, and anything that should not live only in one head.',
        'stat_open': 'Open',
        'stat_total': 'Total',
        'stat_showing': 'Showing',
        'search': 'Search',
        'task_title_placeholder': 'Task title',
        'status': 'Status',
        'all_tasks': 'All tasks',
        'open_only': 'Open only',
        'completed_only': 'Completed only',
        'area': 'Area',
        'all_areas': 'All areas',
        'apply': 'Apply',
        'reset': 'Reset',
        'done': 'Done',
        'no_details': 'No details yet.',
        'general': 'General',
        'edit': 'Edit',
        'delete': 'Delete',
        'no_tasks_found': 'No tasks found',
        'create_first_task': 'Create the first shared task or change filters.',
        'create_task': 'Create task',
        'files_eyebrow': 'Files',
        'files_title': 'Shared vault',
        'files_description': 'Documents, tickets, photos, and files that should be available to both of you.',
        'all_files': 'All files',
        'category': 'Category',
        'everything': 'Everything',
        'favorites_only': 'Favorites only',
        'no_files_yet': 'No files yet',
        'upload_first_file': 'Upload the first shared document or photo.',
        'dates_eyebrow': 'Dates',
        'dates_title': 'Shared calendar',
        'dates_description': 'Birthdays, anniversaries, bills, travel plans, and everything worth remembering.',
        'add_date': 'Add date',
        'all_saved': 'All saved',
        'no_dates_yet': 'No dates yet',
        'add_first_date': 'Add birthdays, anniversaries, trips, and little rituals.',
        'chat_eyebrow': 'Chat',
        'chat_title': 'Daily notes',
        'chat_description': 'Meal reports, small updates, plans, and anything that should stay in your shared archive.',
        'no_messages_yet': 'No messages yet',
        'start_chat': 'Start with a meal report, plan, or tiny love letter.',
        'send': 'Send',
        'delete_message_confirm': 'This message will be removed from the shared chat.',
        'enable_notifications': 'Enable notifications',
        'notifications_enabled': 'Notifications enabled',
    },
    'ru': {
        'brand_subtitle': 'Хаб для пары',
        'nav_home': 'Главная',
        'nav_home_hint': 'Обзор',
        'nav_todo': 'Задачи',
        'nav_todo_hint': 'Туду',
        'nav_files': 'Файлы',
        'nav_files_hint': 'Хранилище',
        'nav_chat': 'Чат',
        'nav_chat_hint': 'Заметки',
        'nav_dates': 'Даты',
        'nav_dates_hint': 'Календарь',
        'nav_settings': 'Настройки',
        'nav_settings_hint': 'Тема и язык',
        'logout': 'Выйти',
        'settings_eyebrow': 'Настройки',
        'settings_title': 'Предпочтения',
        'settings_description': 'Выбери внешний вид OurHome и язык интерфейса.',
        'theme_title': 'Тема',
        'theme_description': 'Переключение между светлым и тёмным оформлением.',
        'theme_light': 'Светлая',
        'theme_dark': 'Тёмная',
        'language_title': 'Язык',
        'language_description': 'Выбери язык интерфейса.',
        'save_settings': 'Сохранить настройки',
        'account_title': 'Аккаунт',
        'account_description': 'Управление профилем, паролем и доступом к аккаунту.',
        'profile_title': 'Профиль',
        'profile_description': 'Измени логин, почту и отображаемое имя в OurHome.',
        'password_title': 'Пароль',
        'password_description': 'Обнови пароль без выхода из текущей сессии.',
        'delete_account_title': 'Деактивация аккаунта',
        'delete_account_description': 'Скрывает аккаунт и запрещает вход, пока он не будет восстановлен.',
        'delete_account_warning': 'Общие пространства и сообщения останутся на месте, но вход будет отключён.',
        'recover_account': 'Восстановить аккаунт',
        'recover_account_description': 'Вернуть деактивированный аккаунт и задать новый пароль.',
        'update_profile': 'Обновить профиль',
        'change_password': 'Изменить пароль',
        'deactivate_account': 'Деактивировать аккаунт',
        'space_label': 'Пространство',
        'group_mode': 'Групповой режим',
        'shared_space': 'Общее пространство',
        'shared_space_description': 'Выбери пространство, создай новый дом или добавь второго пользователя.',
        'active_space': 'Активное пространство',
        'active_space_description': 'Все задачи, файлы, даты и сообщения чата общие внутри этого пространства.',
        'members': 'Участники',
        'members_description': 'Люди, которые могут видеть и менять это общее пространство.',
        'space_owner': 'Владелец',
        'remove_member': 'Удалить',
        'add_user': 'Добавить пользователя',
        'add_user_description': 'Введи существующий username, чтобы дать доступ.',
        'add': 'Добавить',
        'create_space': 'Создать пространство',
        'create_space_description': 'Используй это для отдельного дома, поездки или проекта.',
        'create': 'Создать',
        'dashboard_eyebrow': 'CoupleHome MVP',
        'dashboard_title': 'Добро пожаловать домой',
        'dashboard_description': 'Здесь живёт всё общее: задачи, файлы, даты и ежедневные заметки.',
        'question': 'Вопрос',
        'today': 'Сегодня',
        'answer_in_chat': 'Ответьте на него в чате, когда день станет спокойнее.',
        'favorites': 'Избранное',
        'open': 'Открыть',
        'download': 'Скачать',
        'favorite': 'Избранное',
        'reminder': 'Напоминание',
        'latest_notes': 'Последние заметки',
        'no_notes': 'Заметок пока нет.',
        'favorite_files_empty': 'Добавь важные файлы в избранное, чтобы они были здесь.',
        'events_empty_short': 'Добавь годовщины, дни рождения, поездки и счета.',
        'new_task': 'Новая задача',
        'upload_file': 'Загрузить файл',
        'open_tasks': 'Открытые задачи',
        'completed': 'Выполнено',
        'files': 'Файлы',
        'upcoming': 'Скоро',
        'todo_eyebrow': 'Задачи',
        'todo_title': 'Общий список задач',
        'todo_description': 'Просьбы, дела, планы и всё, что не должно храниться только в одной голове.',
        'stat_open': 'Открыто',
        'stat_total': 'Всего',
        'stat_showing': 'Показано',
        'search': 'Поиск',
        'task_title_placeholder': 'Название задачи',
        'status': 'Статус',
        'all_tasks': 'Все задачи',
        'open_only': 'Только открытые',
        'completed_only': 'Только выполненные',
        'area': 'Раздел',
        'all_areas': 'Все разделы',
        'apply': 'Применить',
        'reset': 'Сбросить',
        'done': 'Готово',
        'no_details': 'Подробностей пока нет.',
        'general': 'Общее',
        'edit': 'Изменить',
        'delete': 'Удалить',
        'no_tasks_found': 'Задачи не найдены',
        'create_first_task': 'Создай первую общую задачу или измени фильтры.',
        'create_task': 'Создать задачу',
        'files_eyebrow': 'Файлы',
        'files_title': 'Общее хранилище',
        'files_description': 'Документы, билеты, фото и файлы, которые должны быть доступны вам обоим.',
        'all_files': 'Все файлы',
        'category': 'Категория',
        'everything': 'Все',
        'favorites_only': 'Только избранное',
        'no_files_yet': 'Файлов пока нет',
        'upload_first_file': 'Загрузи первый общий документ или фото.',
        'dates_eyebrow': 'Даты',
        'dates_title': 'Общий календарь',
        'dates_description': 'Дни рождения, годовщины, счета, поездки и всё, что важно помнить.',
        'add_date': 'Добавить дату',
        'all_saved': 'Всего сохранено',
        'no_dates_yet': 'Дат пока нет',
        'add_first_date': 'Добавь дни рождения, годовщины, поездки и маленькие ритуалы.',
        'chat_eyebrow': 'Чат',
        'chat_title': 'Ежедневные заметки',
        'chat_description': 'Отчёты по еде, небольшие новости, планы и всё, что должно остаться в общем архиве.',
        'no_messages_yet': 'Сообщений пока нет',
        'start_chat': 'Начни с отчёта по еде, плана или маленького милого сообщения.',
        'send': 'Отправить',
        'delete_message_confirm': 'Сообщение будет удалено из общего чата.',
        'enable_notifications': 'Включить уведомления',
        'notifications_enabled': 'Уведомления включены',
    },
}


def ui_text(request):
    language = request.session.get('language', 'en')
    if language not in UI_TEXT:
        language = 'en'

    return {
        'ui': UI_TEXT[language],
        'current_language': language,
    }
