# Generated by Django 6.0.6 on 2026-06-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_assign_existing_items_to_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('voice', 'Voice'), ('video_circle', 'Video circle')], default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
